name : merge entre brachs

on:
  push:
    branches:
      - develop
jobs:
  merge_to_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Merge to main
        run: |
          git checkout main
          git merge develop
          git push origin main
