 name: Deploy to GitHub Pages
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.PEDRA_ACESSO }}  # Certifique-se de que o token tem permissão para fazer push para a branch 'gh-pages'
    publish_dir: ./dist/pokedex/browser/pokemons  # O caminho onde os arquivos finais são gerados
    publish_branch: gh-pages  